language: java
jdk: oraclejdk8
before_script:
- cd BackendProject
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: Hu6hXGJHl4SG+xAQ6THNLfZxHOjrRQQu4qP6dyBybXWIptbAfeGMNSQbq++r9UFYksBZq6A71VP36Ma3dzTBS3IE5JSQb2mkpZFfyvMVVJLLaBrjKeEPDHB1gNHN9VDAfTgNSbNreK+4VbNPEo8pVMWkpG4pNIwPWVnI2Z8cRrO/4Dv1pidujwNoG4Tq98nggUWinc5M/SK3o89bdFVDQsdrPF+m838NWY/LqhPDe7x37fLf5u5B3N9IgifzPR2dLXHIMkjRn3CyCr/XM85NmWqjpTrTOb5PKhylNFpyNI5zoP3eF8pWCz1G6AZdELBWI92IimUOM7Rtgb17S+U2aSsg9bwG2oTx0BguoD1bsjszCgFY1mUWMAWastsVB7Va6KtZs4dCwo3M0ByaEoieaCl0Y4U9Mm4wFWp7PAH/bl9l4jXN4y24K+Umhr7RKwQodPfE0L/j46pXzQkR5SvRYacJathp+Mj+AdN4UtjO8GCm5LezfhUTZmlhD1vB5TzTK4Fs3rN/vxhA8dHPS6MQgbYK9mvxpurLFjgHxyZvau2MDWN6y11iojbiVvcxNNgL2y983PdUsKVI5OAq7M4N17NC3V/7SGXEZ39J8fbnOfmmkfzyWtMEF/Nb5yPFlywrsOLQfKhhDQtfzcjOsQvB14YK4SzRuKLkTJJ8KPFiEdM=
  app:
    master: feedback-analysis-grp-app
    calculator: feedback-analysis-calculator
notifications:
  webhooks:
    urls:
    - secure: SNWN50K7UV8H9Ex8a42iKiW9uiBXu5sqCvkfGVyM/rlOFIa5zSeRCbyR+920uv6HMqqehcnRGch3psm0fgeqnvvM1ZFl0/FWnWi0GsYfiqIdE8SZagcA0PFhSLqW9qcaT5D1O7pzDfTo6MWF16HnAJ1seyhbipVZQJ919l2j0RcYEcKXWEePJSn+ywGC95ospCk+gNtWKp5Y0/r5KDMQaWE2xU+zB2FbLnwhusveAzBJhCpY5hMa+cXkLlOFkkD+3Tt9DVD5yIdvHNhBoj5El3MruFd7RjsZ26Grj0QP5G2d/LPZF9e3X4//7tBpjXgy4h2vGejZ+SFfaFoGekM3fRca1zui1Z5SU/aunG1CDxKt0mHeno0PEwqEnqDtMe+VnH0uLfv1pc2LPhhOhW5+xC03be23fPUaLK3t0mvKMhzRun8PsdQfd37dWHwnU5dIYB4o6aEr1lkmfA3+pBexM9xpEidkte5UKaoTE3PVv92XEZD2QXq8GYQAe3j9BuM14BMlyHVEBhDdkttrNNKKSwIL4Ohf079/D/nfeyYC/BFsbXIewf/32+B8NldZg3gqBOa+04hZacNHwJ4jFe4WiypOpVxiAXvVVt1quolPIVNOrX14C9Rw3Utb/ZAPp5at+zxTDTpQmLSWwblDreOP6FQA41+JndJu/RqyvFavxYY=
