language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: E9taIj4AB4IqWrnJCBB11FG0/AEYw79kmMd9qe7Ln+OZ1EgRj0UWWL8Q+xk/sYDYpNn5WlVx8ZaLHx1ObgIgilvsYAJ0D7PIYabItWNvrvyB20uafZCsgUua+/tD6j2W6tAqAcSPxpFltW5JfPgeQSpvJ1zijbDtZrJ8ATOYOMf3SZb+tk47slMDoTwsxvIlkhH3yBByIqb7ncdD+7P030Qf13T1NVlCNq28Mw8+pUfuuP94P/IxWyJLj+3aP3eNIZG8mHNExdcsmAI+1gEe28nGHSi/dLk4D/N6AqY9csoQP0bwlaa1hIqulmhd3jsAtWv2r7K3t6u412Hdl7/bX7ouux8ItjqjVOq0AoH6syngJEsEbMaMUXCLuemiyyigsCPar/ipLSf0LCW7fPpE2TywHQXxtdOyr1DDt/rlECj6Lra1mNN8kxfTqaqKkZFjD+r55EYdfm31LJSACLqxgo8Ky2LXn51M/aBVfhzNWTEwk4tTOLew0x1SU0LP6eRnPc2YhH0JKm7Ox+/IwPrtdGFG33tXBeIqHNDHL/HA5UNXB/ZYBnRBPPCeyPUv/dZb1KnF4kqTsqVCWV+T6KH3K7TdqerUvaWfNOsgrig7nxf0Yq+oT3sEpCTlR9pnJLwbkFj2Q307OKPY0k9kaoJRaE8dVa0+bpL7lWX6pekUXnk=
  app:
    master: feedback-analysis-app
    calculator: feedback-analysis-calculator
