language: java
jdk: oraclejdk11
before_script:
- cd BackendProject
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: Nvpg4YIDp9EkEbWuIPDjlLcogRLi6v6AF5D3AXN7UulYzjjrgraU+V3OpnDHdpYoc/HcwaVyxMzE3IfPS6B85qWJNOu6dSnpVXtDsaYOTp0RqLFJ6+oyhiOap98gU56E738zqzzugYBk44Recgy1veXAhBmVOY1hg0subi7d+PGi6+OymO8H4UgK6nbgoi+SBo8B8xOznW0+3bMyrM55YVBCRpiE0Y1IlDtEnY7vPe/Gknw833LA6w6Yv6qviBC6m27HWLhWz+N6xW8tygSlBrcypyjllkxg72A6qRVFeHPSaIPn9rh5I2UELiIiFsX4IKD3WRKicmC7WFqv8QFmBSFFqCwXIlX79WxKsZ5UVRHJgvBS8hMJwiXhFUcd0KAFk0fMNlvOwQAMru3NJSZn83vIOffoGAgk6Ggf1Vb5rCvfQfZekkPbjAnZlc77P4lvb1NSedulNdhdmH8rkeyKOU4ZkJDAxEVHhIubMXCEg/j2hYTBS3LhXAwDRNEOO7nJ7sZi23VQKQMhIOI1lcceOQ9kdZubpOpYyG9lDPa2B/4SQTDq3EMXJrvXWmUQ1Rmg5QrND/M7s6IrQxZtPqILYVC87+7/gGH+jRovTHml3pRNEu1aqLJbndrbr+g1rxGkaDL95VJ2r2Uw81lGsJrxPH+sR/TvwdbM+FQ7O1Yjjgs=
  app:
    master: feedback-analysis-grp-app
    calculator: feedback-analysis-calculator
notifications:
  webhooks:
    urls:
    - secure: SNWN50K7UV8H9Ex8a42iKiW9uiBXu5sqCvkfGVyM/rlOFIa5zSeRCbyR+920uv6HMqqehcnRGch3psm0fgeqnvvM1ZFl0/FWnWi0GsYfiqIdE8SZagcA0PFhSLqW9qcaT5D1O7pzDfTo6MWF16HnAJ1seyhbipVZQJ919l2j0RcYEcKXWEePJSn+ywGC95ospCk+gNtWKp5Y0/r5KDMQaWE2xU+zB2FbLnwhusveAzBJhCpY5hMa+cXkLlOFkkD+3Tt9DVD5yIdvHNhBoj5El3MruFd7RjsZ26Grj0QP5G2d/LPZF9e3X4//7tBpjXgy4h2vGejZ+SFfaFoGekM3fRca1zui1Z5SU/aunG1CDxKt0mHeno0PEwqEnqDtMe+VnH0uLfv1pc2LPhhOhW5+xC03be23fPUaLK3t0mvKMhzRun8PsdQfd37dWHwnU5dIYB4o6aEr1lkmfA3+pBexM9xpEidkte5UKaoTE3PVv92XEZD2QXq8GYQAe3j9BuM14BMlyHVEBhDdkttrNNKKSwIL4Ohf079/D/nfeyYC/BFsbXIewf/32+B8NldZg3gqBOa+04hZacNHwJ4jFe4WiypOpVxiAXvVVt1quolPIVNOrX14C9Rw3Utb/ZAPp5at+zxTDTpQmLSWwblDreOP6FQA41+JndJu/RqyvFavxYY=
