language: java
jdk: oraclejdk11
before_script:
- cd BackendProject
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: LX6N2EOxbfReaFnXxZpf5zV2czlnjGoZ0PZkb+NjnFVT9vl9NoS8FvWdPBCk7DzDNaEdTm9ThuMH/rcW29cLchZnAiX1DfA7h9l9XC6IajmBmnMuiCxe2btjc0RBm+sWkJdI2T0lZ5t4KSjHUCodYl5zg4lwzZeNjchaZCMFDSvTNcbI7f0TeTBDmBnW3fxNqbfvnT3hdrNv152swc06TS1lDWg6ocYpSGcdhULWBAnt2C6rz+nWCEzImbZBd57059+qypsLt/vZYz33unCu3tazuXRO8F/xZ2OSRnNocvE2xO0GROnDAPnwTqGLl6i2DhskWKusbeg/ZBnS5Cvf+sh4bTdyshRhIgyA3JQgC9OlPccua4UihraMTFUu9zXmdRAOcjJMKwe7UpkEpvsy52TZLmTiHeZH31DIElZZb9nQAJXrBQbr5cgbINAqgqrBxh3zP4vw5Bl4I8OPIJ+fgMIETvpk4AQkeTADEcZmmiq1KLiFVH1rYSa17aOf4U+gXiC9QRIPEskSOBgTkHLix18dUuUwP+gvEjwP1PeMgEXk7NTq4GAqg2ZsB0VJpplUYYArn3wIsNcpesJcAaGayszs8bvo8ESVdxSpWEcrsOwZ25aJELWLq1OYhmM1Se9puYcvkfUIdUXtvQCU9BBTQlKSx55a5ArXxIr+FM/HnLI=
  app:
    master: feedback-analysis-grp-app
    calculator: feedback-analysis-calculator
notifications:
  webhooks:
    urls:
    - secure: SNWN50K7UV8H9Ex8a42iKiW9uiBXu5sqCvkfGVyM/rlOFIa5zSeRCbyR+920uv6HMqqehcnRGch3psm0fgeqnvvM1ZFl0/FWnWi0GsYfiqIdE8SZagcA0PFhSLqW9qcaT5D1O7pzDfTo6MWF16HnAJ1seyhbipVZQJ919l2j0RcYEcKXWEePJSn+ywGC95ospCk+gNtWKp5Y0/r5KDMQaWE2xU+zB2FbLnwhusveAzBJhCpY5hMa+cXkLlOFkkD+3Tt9DVD5yIdvHNhBoj5El3MruFd7RjsZ26Grj0QP5G2d/LPZF9e3X4//7tBpjXgy4h2vGejZ+SFfaFoGekM3fRca1zui1Z5SU/aunG1CDxKt0mHeno0PEwqEnqDtMe+VnH0uLfv1pc2LPhhOhW5+xC03be23fPUaLK3t0mvKMhzRun8PsdQfd37dWHwnU5dIYB4o6aEr1lkmfA3+pBexM9xpEidkte5UKaoTE3PVv92XEZD2QXq8GYQAe3j9BuM14BMlyHVEBhDdkttrNNKKSwIL4Ohf079/D/nfeyYC/BFsbXIewf/32+B8NldZg3gqBOa+04hZacNHwJ4jFe4WiypOpVxiAXvVVt1quolPIVNOrX14C9Rw3Utb/ZAPp5at+zxTDTpQmLSWwblDreOP6FQA41+JndJu/RqyvFavxYY=
