language: java
jdk: oraclejdk8
before_script:
- cd BackendProject
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: K4YX7yhZMK5hw5gjuYnSK04/5oJB6kIiHn4IqTlVH/l57XhYFVCfUdnQ7JxPwUKbyDrUsocOlXR+xyhNVTslG+57XYK2NQXk+oTLy/yK6+EJdjfhwmgwYvS37gt/Zx7E4yDpFgRO43PReozVzRFR+pzEBfuqXYNnw2zEd0aEKa115DSGxYd84aV8MDNShoYGGEa5XhwVgBEb1RzDqrfmthEZk/qSXo0OuA/4pYuDpg1mGLlZrEexc2tGPSNn0B5VJlvWYJSFBHCtmiNjt3lmM0K4PohP5WzfN83SHN1jhaEftwqmr3TMUZJ20HMncB+WYeCyoK47QkTfGV7e/Ox9fUInMLF5D0ND0kmW7ZPAFFihSt9OW2HICXYJREfvJpH8HZZdkyUR6jjlp6kGpBJqo0j5zRnEnd0O/peLa1ISqmUII/gKGkgUmJCcLCaoe/aO8EuKY8EriGsFYWo276c6EKZ1K37C1FNoHz9Kx1jgeIs/D8tzM+kATQ0SEwB4fQi0goqwergc0LQEeUg0n6XHsCKgHFDZIOTR2OXw+dXIU+8+DpqvhJ3VE0H+63ZllmmjksieDDCyTWH6rrm+sOY3COxRAb0M6ldOPaFHM9eQRDGXvria6sOeW0QkJpwpTfeLf2P8NK1YTSTZmtvNkCQb8i+Pn9Vb+uqihYeQ6reMCuk=
  app:
    master: feedback-analysis-grp-app
    calculator: feedback-analysis-calculator
notifications:
  webhooks:
    urls:
    - secure: SNWN50K7UV8H9Ex8a42iKiW9uiBXu5sqCvkfGVyM/rlOFIa5zSeRCbyR+920uv6HMqqehcnRGch3psm0fgeqnvvM1ZFl0/FWnWi0GsYfiqIdE8SZagcA0PFhSLqW9qcaT5D1O7pzDfTo6MWF16HnAJ1seyhbipVZQJ919l2j0RcYEcKXWEePJSn+ywGC95ospCk+gNtWKp5Y0/r5KDMQaWE2xU+zB2FbLnwhusveAzBJhCpY5hMa+cXkLlOFkkD+3Tt9DVD5yIdvHNhBoj5El3MruFd7RjsZ26Grj0QP5G2d/LPZF9e3X4//7tBpjXgy4h2vGejZ+SFfaFoGekM3fRca1zui1Z5SU/aunG1CDxKt0mHeno0PEwqEnqDtMe+VnH0uLfv1pc2LPhhOhW5+xC03be23fPUaLK3t0mvKMhzRun8PsdQfd37dWHwnU5dIYB4o6aEr1lkmfA3+pBexM9xpEidkte5UKaoTE3PVv92XEZD2QXq8GYQAe3j9BuM14BMlyHVEBhDdkttrNNKKSwIL4Ohf079/D/nfeyYC/BFsbXIewf/32+B8NldZg3gqBOa+04hZacNHwJ4jFe4WiypOpVxiAXvVVt1quolPIVNOrX14C9Rw3Utb/ZAPp5at+zxTDTpQmLSWwblDreOP6FQA41+JndJu/RqyvFavxYY=
