language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: GWQ+uYRFdJt0TNy1p4fMloUxWN07XiOioRGGqgmdw9UZb5BQr+HTKpFaARaNRrMjG5L2Doaj1rLGE6wgMs4mzbiEfD8jlIkbm92K/hJfEVub4XyK5XKkas/AQS6cOwmA0HhFRluq4JADf4Jl1JpGdDerxAGmnqQ6K5Jrl+JzNsffiw50ue+xtehHEQu+xxV+OpB58ehZBmKN6Hvhg9IsFPii6f9a538742Sf2qsHgWcRpbo3geCTiYDcOb2RwBchb5k+X7ZeE/iZLOcfS7avXgIc3pFntbQhV4dEMg5P01D5trrlnwm+hKI3FSfy54AcrbVpcOU9nALSJoz8xwN+C0ZmQeAp6e755ZCJdaQ7Y2Abuiv44K7gXUQps1QNPiqjnK8aALa/sFPn4vgbSHgwgXvoPeb9iNUnrt+rEPP/8F4PxtNrDt5ktMvLND//TtpoTj8NMslC6jygPaHrjLVJTHQzs18NgifHbNSCWZznoETA87VmLaA45cYlhtIqF1AIQYYuJMOJjn2pQ0clpT2to9vwB7m3XRFLE8KHyhu5wvwD/stUd3mjKb7zhvMlgMSPKGrZpPQvG/1VJKvETh1JBvqQfwga5WpEUG5fokoItkNBS4M7HmjP4GyXcq2Bi0gGT4PEyQG7+ktiLpbBtSREisYW1rhm2oemDiQd69sp8TA=
  app:
    master: feedback-analysis-app
    calculator: feedback-analysis-calculator
