language: java

before_script:
  - cd BackendProject

script: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

deploy:
  provider: heroku
  api_key: 6b2f6e8e-142f-4347-b715-ebb6e6d1aa44 # need to encrypt the api key 
  app: feedback-analysis-app
