language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: kzVq4L5vd6Q/0shI2iDji+nTRRCmHu4MJIObeASNCiNWW8jlr6PSxid5V6HX8VcGeElABqxPa2yzub+au4PQjDOQAWyGC2QN5QgoZ9rQcrMaXPBkYcQBxkQfj32grPQyk9vxvXG3wX8p1pswFxjoUC5ONivvRihRpujgrV7ZvqYTdsF+hD7uTFymWxPL0uWukwVsa9KjHJdyUjgC3dVMI7eXt7x+RMFxci3DWGvOEakME6b9h3OX+417z6BEvgrtK+g6YhVEF/JP/L9Lu/VUvKoTolFDW2WeAW8sCS3+NrMfy2PpJAoogZVzi+M3P4l+F2uhbIGGigZAkDl0K5nlHaggxflCTDjxC4vtJQmpQY8jnZPvwbWIQDrPqPRmR9zlq7tp/oQWf/XfX4Sjiuodwg7uU5slfAPIv0S+e4GsW9iJrLyOJNkLuIEChztikGWsGM3HkBm+Cb9FCYh0UgZjNyjIvPRy/pZmkhcSKdUDkLXQjvY2JoPam41lYOz3kW/fIfZ0I0qTpPQuC7JQcRaRKMg5MjF+C1eCICBpNK+uofjo5vKsHGuVBUpDgsfri5qmokakglNC/TdiqpiODzdelzxnklkRpdmTNwDrTNulDmuoZ9+Kd0sqchhZnQvgjMctv9nvAWsYQCUTjW0+0KAu2OWD98N+1+iLdFNlaqP9x3k=
  app:
    master: feedback-analysis-grp-app
    calculator: feedback-analysis-calculator
