language: java
jdk: oraclejdk11
before_script:
- cd BackendProject
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: T/McrgLaMPAjpT2dT1lASdmeQsWpue4roIKhe2YUy+fThJJsmxZ2I+DkuUmMmjzZj3VrWWQUBulonhHRPgbigL2fvHyNv0gsSlxJjlnSwksySTiKDt6zOGq+r6C2DlaqFmdd3qKFlJRNa7BX1/aOQkI5RpyIH6E7uhnozqb0x6AhpX9bvEc8zBy5nE8wx82urj2oGmcb2CCLnB5JRhh1+WPOLWD0IUV9N9ji+m/z7kpEBvARuMTQoYjeF3vjZ0oBUeExakVWEy43xPeSp7KLz4TZJQlLYjwwnH//9ZqZk0xILio1cAs5v2FN34hgFQSZnMksB1gVsihU94n8v0jxWoEITgk2S4Gu1Q/D8V3VzEMRzH7KwtDehxGUcpqslXxUg/qwFB/8mJo0Y3pLG9AcSXIM+6KBds5DVS02PGfUTnyQjgRtOW72hcO4PCkUy/k5MXV15Zk8m2CNFJgn009IbwE6/EdfslWw0zvVngajRAQDR4cvH7JF6X31C4PX6InontW1gmC9YMCdLNRLFgS6eKZpZvvEzKqAKP0z537L1036O4U4qxb3LR07T90P/SvjvDbTaLF56bvwN4RSBSQr+keegYQTs8Hv5N6SkllBeRA2Dqpl/rITVD2Vmi9P+diN+SxQ1Qz5ZWhq/ABug/VZmqMvWuECfStWg8CowExVPb4=
  app:
    master: feedback-analysis-grp-app
    calculator: feedback-analysis-calculator
notifications:
  webhooks:
    urls:
    - secure: SNWN50K7UV8H9Ex8a42iKiW9uiBXu5sqCvkfGVyM/rlOFIa5zSeRCbyR+920uv6HMqqehcnRGch3psm0fgeqnvvM1ZFl0/FWnWi0GsYfiqIdE8SZagcA0PFhSLqW9qcaT5D1O7pzDfTo6MWF16HnAJ1seyhbipVZQJ919l2j0RcYEcKXWEePJSn+ywGC95ospCk+gNtWKp5Y0/r5KDMQaWE2xU+zB2FbLnwhusveAzBJhCpY5hMa+cXkLlOFkkD+3Tt9DVD5yIdvHNhBoj5El3MruFd7RjsZ26Grj0QP5G2d/LPZF9e3X4//7tBpjXgy4h2vGejZ+SFfaFoGekM3fRca1zui1Z5SU/aunG1CDxKt0mHeno0PEwqEnqDtMe+VnH0uLfv1pc2LPhhOhW5+xC03be23fPUaLK3t0mvKMhzRun8PsdQfd37dWHwnU5dIYB4o6aEr1lkmfA3+pBexM9xpEidkte5UKaoTE3PVv92XEZD2QXq8GYQAe3j9BuM14BMlyHVEBhDdkttrNNKKSwIL4Ohf079/D/nfeyYC/BFsbXIewf/32+B8NldZg3gqBOa+04hZacNHwJ4jFe4WiypOpVxiAXvVVt1quolPIVNOrX14C9Rw3Utb/ZAPp5at+zxTDTpQmLSWwblDreOP6FQA41+JndJu/RqyvFavxYY=
