language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: M2KSTUmyUEEEBq6jSF3dGSp6yJEt4LsOYsd2amOkkd7FZooSZBnU9CcBX7e66GJgnroLv07tqEs8X4rRqqYCI6IKMGNCF4wkk4Bwl+BY6pyFtgbgFt2B28lfBrIrCk+aKUA1RhtHteNjJsyHkodkSfXplCWWkrO82HAiUmkndJ1A9n1BPxNes2RnyVWzBXoQkAaiIIc6SXrFzEa0LaZ28o4ZH5CinqoWHrRe3M8ApzDWoo3vKQ0ek3mK1Z0OcV/TLjIqLIk6luAOzQshziUoqxDmPzkPPon98jm7/m84jr+gn8FSj+BUnZ4LubKzI381mUc1CRmblmtk82KmGOj7Ci2HfZZu+prFBKFbj5iYaK8ZvmzsjO13QJMXGpSaDYLHQ8Sz6jY9iavtG1bsE+meKXf2vQvp+YsENBp+Hp76sXZtiq0nftmupaLhHnpWQx90MUDO8SgEfFnCtdZ2quvqvRsclDVujwc02kVg7s4C2VY0Ibi8uJKsq1SZclJ5dNnAfuS5SvNqQgQbdOguKJJ9rh/7n0SBPoFGqgG2KCSaqRDeyvFSQNh4xxQJ8yZc2JAP6rBliC0MSxMIlIuBs2fPsrY43JaVus5XR3xiXzSfFOMztdcpd6UoPrRR8IXvzzrMb/By1aEMQAWuddzRpg4ec7hqHpGsZBGo47kBBoYGuw0=
  app:
    master: feedback-analysis-app
    calculator: feedback-analysis-calculator
